---
#Install updates on Fileserver group paralell

- name: Windows-Updates mit VMware-Snapshot
  hosts: acmpms01
  serial: 1
  #  strategy: free
  tasks:
    - name: Create a snapshot, auf Gross/Kleinschreibung des Hostnamen achten
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: /
        name: "{{ inventory_hostname_short }}"
        state: present
        snapshot_name: snap_ansible
        description: Snapshot_von_Ansible
      delegate_to: localhost

    - name: Logfile auf Remote Server loeschen
      ansible.windows.win_file:
        path: C:/ansible_{{ inventory_hostname }}.txt
        state: absent

    - name: search and install updates und Logfile schreiben
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
            #state: searched
        reboot: yes
        reboot_timeout: 1200
        log_path: c:\ansible_{{ inventory_hostname }}.txt
      register: update_result

    - name: Update-Log abholen
      fetch:
        src: C:/ansible_{{ inventory_hostname }}.txt
        dest: /tmp/
        flat: yes
      register: update_result

    - name: Update-Status per Mail
      community.general.mail:
        to: "{{ mail_to }}"
        subject: System {{ ansible_hostname }} has been successfully provisioned.
        attach: /tmp/ansible_{{ inventory_hostname }}.txt
      delegate_to: localhost
