---
# Show Status Windows Updates
# 1 server parallel

- name: Windows Updates Status
  hosts: all
  serial: 1
  strategy: linear
  tasks:

    - name: Search-only, return list of found updates (if any)
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
        state: searched
        reboot: no
      register: win_updates

    - name: print variable
      debug:
        msg: '{{ win_updates.updates }}'
