---
- name: Delete GlobalProtect Gateway Config
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ external_firewall }}'
    cmd: delete
    xpath: |
      /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']
      /global-protect/global-protect-gateway/entry[@name='GlobalProtect Gateway']/remote-user-tunnel-configs/entry[@name='Ansible-Test']
# notify: Commit external firewall

- name: Set GlobalProtect Gateway Config
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ device }}'
    xpath: |
      /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']
      /global-protect/global-protect-gateway/entry[@name='ansible-test-gw']/remote-user-tunnel-configs/entry[@name='test-client']/split-tunneling/access-route
    element: |
        <access-route>
        {% for route in teams_routes %}
             <member>{{ route }}</member>
        {% endfor %}
        </access-route>

# notify: Commit external firewall