---
- name: Demonstrate how to use OP module to execute various op commands on PANW device
  hosts: all
  connection: local
  # gather_facts: no

  collections:
    - paloaltonetworks.panos
    
  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") | default(omit) }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

  tasks:
    - name: Download EDL for MS365 - Any
      get_url:
        url: https://saasedl.paloaltonetworks.com/feeds/m365/worldwide/any/all/ipv4
        dest: /var/tmp/ms365_list.txt

    - name: Read O365 IP list into fact
      set_fact:
        teams_routes: '{{ lookup("file", "/var/tmp/ms365_list.txt").splitlines() }}'
        
    - name: Set GlobalProtect Gateway Config
      paloaltonetworks.panos.panos_type_cmd:
        provider: '{{ device }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']
          /global-protect/global-protect-gateway/entry[@name='ansible-test-gw']/remote-user-tunnel-configs/entry[@name='test-client']/split-tunneling/access-route
        element: |
            <access-route>
            {% for route in teams_routes %}
                 <member>{{ route }}</member>
            {% endfor %}
            </access-route>

    # notify: Commit external firewall

