---
- name: Demonstrate how to use OP module to execute various op commands on PANW device
  hosts: all
  gather_facts: no

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Show all interfaces using
      panos_op:
        ip_address: '{{ lookup("env", "ip_address") }}'
        username: '{{ lookup("env", "username") | default(omit) }}'
        password: '{{ lookup("env", "password") | default(omit) }}'
        cmd: "show interface all"
      register: result

    - name: returned output in the default JSON format
      debug: msg='{{ result.stdout }}'
